# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97d764e72763fd96602cf75a250d11e06d42af404c4c3260b31b328646f1f33d0e92f74e3fd8a25d3905c8d87b7490062cb6384b15efcd2458b0c8b415584276

test:
  secret_key_base: 67df8b582735fa8f1d197c9ed700543c16b219d3ebb41e281f4b8a1d593664f90b414882a24f1746b890820d7e8fbb473bdb6a17967c9b02757648f90776e4c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
